name: Build MAUI Installer

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install WiX Toolset v6.0.1 CLI
        run: |
          Invoke-WebRequest -Uri https://github.com/wixtoolset/wix/releases/download/v6.0.1/wix-6.0.1.zip -OutFile wix.zip
          Expand-Archive wix.zip -DestinationPath $Env:ProgramFiles\WiX
          Remove-Item wix.zip
          $env:PATH = "$Env:ProgramFiles\WiX;$env:PATH"

      - name: Publish MAUI Application
        run: |
          dotnet publish ./src/MyMauiApp/MyMauiApp.csproj -c Release -r win-x64 --output "${{ vars.BUILD_OUTPUT }}"

      - name: Compile Product.wxs
        run: |
          candle.exe ./installer/Product.wxs -dSourcePath="${{ vars.BUILD_OUTPUT }}"

      - name: Link Product MSI
        run: |
          light.exe Product.wixobj -out "./artifacts/${{ vars.MSI_NAME }}"

      - name: Compile Bundle.wxs
        run: |
          candle.exe ./installer/Bundle.wxs

      - name: Link Bootstrapper EXE
        run: |
          light.exe Bundle.wixobj -ext WixBalExtension -out "./artifacts/${{ vars.EXE_NAME }}"

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "./artifacts/${{ vars.EXE_NAME }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
