name: Build MAUI Installer

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Setup WiX Toolset
        uses: joncloud/wix-installer@v1
        with:
          version: '4.0.4'

      - name: Publish MAUI app
        run: |
          dotnet publish src/MyMauiApp/MyMauiApp.csproj `
            -c Release -r win-x64 `
            --output "${{ vars.BUILD_OUTPUT }}"

      - name: Build Bootstrapper UI
        run: dotnet build src/BootstrapperUI/BootstrapperUI.csproj -c Release

      - name: Compile Product.wxs
        run: |
          candle.exe installer\Product.wxs -dSourcePath="${{ vars.BUILD_OUTPUT }}"

      - name: Link MSI
        run: |
          light.exe Product.wixobj -out "artifacts/${{ vars.MSI_NAME }}"

      - name: Compile Bundle.wxs
        run: candle.exe installer\Bundle.wxs

      - name: Link Bootstrapper EXE
        run: |
          light.exe Bundle.wixobj `
            -ext WixBalExtension `
            -out "artifacts/${{ vars.EXE_NAME }}"

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/${{ vars.EXE_NAME }}
